print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "C:/Users/betha/OneDrive/Desktop/UVU-FA~1/DGM222~1/_UNITY~1/PogoGame/Assets/GameArt/Maya/BirdCage.ma"`)
{		
	file -o "C:/Users/betha/OneDrive/Desktop/UVU-FA~1/DGM222~1/_UNITY~1/PogoGame/Assets/GameArt/Maya/BirdCage.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/betha/OneDrive/Desktop/UVU-FA~1/DGM222~1/_UNITY~1/PogoGame/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "C:/Users/betha/OneDrive/Desktop/UVU-FA~1/DGM222~1/_UNITY~1/PogoGame/Temp/CommandPipe";

$donepipeKill = `fopen "C:/Users/betha/OneDrive/Desktop/UVU-FA~1/DGM222~1/_UNITY~1/PogoGame/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
